# Copyright 2020 NXP Semiconductors
# This page was inspired on MediaPipe page: https://github.com/google/mediapipe
# SPDX-License-Identifier: BSD-3-Clause

remote_theme: pmarsceill/just-the-docs

logo: idocmx

search_enabled: true
search_tokenizer_separator: /[\s/]+/

heading_anchors: true

aux_links:
  "Source Code Available on GitHub":
    - "https://github.com/diegohdorta/idocmx"

footer_content: "<a href=\"https://raw.githubusercontent.com/diegohdorta/idocmx/master/LICENSE.md\">LICENSE TERMS</a>"

color_scheme: nil
